# Funding and Sponsorship Options for BRAINTREE Cybersecurity Profile

# Cryptocurrency Donations (Primary - Preferred for Security Research)
custom: ["https://github.com/Braintree-Tools/Braintree-Tools/blob/main/README.md#support-my-work"]