name: Update Profile Stats

on:
  schedule:
    # Update stats every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      metadata: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update README with recent activity"
          MAX_LINES: 10
          GH_USERNAME: "Braintree-Tools"
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          TARGET_FILE: "README.md"
          EMPTY_COMMIT_MSG: ":memo: empty commit to keep workflow active after 60 days of no activity"